languageCode = "de-DE"
languageName = "Deutsch (Deutschland)"
languageDirection = "ltr"
weight = 4

title = "Gabriel Moura"
copyright = "&copy; 2024 Gabriel Moura"

[params]
  dateFormat = "2. January 2006"

  mainSections = ["samples"]
  description = "Ein leistungsstarkes, leichtgewichtiges Theme für Hugo, das mit Tailwind CSS erstellt wurde."

[params.author]
  name = "Gabriel Moura"
  image = "img/midjourney3.png"
  headline = "Ich lerne Deutsch"
  bio = "Dies ist ein Beispiel für eine Autorenbiografie, und obwohl hier ein Stockfoto eines Hundes zu sehen ist, wurde dieser Artikel tatsächlich von einem Menschen verfasst. :dog:"
  links = [
#    { x-twitter = "https://twitter.com/" },
#    { facebook = "https://facebook.com/" },
    { linkedin = "https://www.linkedin.com/in/gabriel-moura-macedo/" },
    { github = "https://github.com/gmmacedo" },
    { gitlab = "https://gitlab.com/gmmacedo1/" },
#    { youtube = "https://youtube.com/" },
  ]

