languageCode = "en-AU"
languageName = "English (Australia)"
languageDirection = "ltr"
weight = 1

title = "Gabriel Moura"
copyright = "&copy; 2024 Gabriel Moura"

[params]
  dateFormat = "2 January 2006"

  mainSections = ["samples"]
  description = "A powerful, lightweight theme for Hugo built with Tailwind CSS."

[params.author]
  name = "Gabriel Moura"
  image = "img/midjourney3.png"
  headline = "Geology student pretending to be a data scientist"
  bio = "Just a student thirsty for knowledge and amazed by rocks, minerals and tecnology"
  links = [
#    { x-twitter = "https://twitter.com/" },
#    { facebook = "https://facebook.com/" },
    { linkedin = "https://www.linkedin.com/in/gabriel-moura-macedo/" },
    { github = "https://github.com/gmmacedo" },
    { gitlab = "https://gitlab.com/gmmacedo1/" },
#    { youtube = "https://youtube.com/" },
  ]
