baseURL = 'https://gmmacedo.github.io/'
languageCode = 'pt-br'
title = 'Gabriel Moura'

defaultContentLanguage = 'pt'
defaultContentLanguageInSubdir = true
enableMissingTranslationPlaceholders = true

[services]
  [services.googleAnalytics]
    id = 'G-XS61PN2LXC'

[markup]
  [markup.highlight]
    noClasses = false
    style = "monokai"

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[languages]

    [languages.pt]
        languageName = "Português"
        weight = 1
        title = "Gabriel Moura"
        languageCode = "pt-br"
            [languages.pt.params]
                description = 'Estudante de geologia, entusiasta da tecnologia, compilando a natureza.'
                dateFormat = 'January 2, 2006'

    [languages.en]
        languageName = "English"
        weight = 2
        title = "Gabriel Moura"
        languageCode = "en-us"
            [languages.en.params]
                description = "A geology student, tecnology enthusiast, compiling nature"
                dateFormat = 'January 2, 2006'

    [languages.pt.menu]
        [[languages.pt.menu.main]]
        identifier = "about"
        name = "Sobre"
        url = "/pt/about/"
        weight = 1
        
        [[languages.pt.menu.main]]
        identifier = "posts"
        name = "Blog"
        url = "/pt/posts/"
        weight = 2

    [languages.en.menu]
        [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/en/about/"
        weight = 1

        [[languages.en.menu.main]]
        identifier = "posts"
        name = "Blog"
        url = "/en/posts/"
        weight = 2
